# Generated by Django 4.2 on 2026-01-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_count', models.IntegerField(help_text='Number of rows in CSV')),
                ('avg_flowrate', models.FloatField(help_text='Average flowrate')),
                ('avg_pressure', models.FloatField(help_text='Average pressure')),
                ('avg_temperature', models.FloatField(help_text='Average temperature')),
                ('type_distribution', models.TextField(help_text='JSON: count per equipment type')),
                ('original_data', models.TextField(help_text='JSON: original CSV data')),
            ],
            options={
                'verbose_name_plural': 'Dataset Summaries',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
